language: cpp

addons:
    apt:
        sources:
            ubuntu-toolchain-r-test
        packages:
            - gcc-8
            - g++-8

before_install:
    - sudo apt-get install -y git make

before_script:
    - export PATH=/tmp/apps/minunit/bin:$PATH
    - export LD_LIBRARY_PATH=/tmp/apps/minunit/lib:$LD_LIBRARY_PATH
    - cd /tmp
    - wget https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.sh
    - sh cmake-3.10.3-Linux-x86_64.sh --prefix=/tmp/apps/minunit
    - cd /tmp
    - git clone --recursive https://github.com/nanolith/cbmc cbmc
    - cd /tmp/cbmc && git checkout develop
    - mkdir build && cd build
    - CC=gcc-8 CXX=g++-8 cmake -DCMAKE_INSTALL_PREFIX=/tmp/apps/minunit ..
    - make -j4
    - mkdir -p /tmp/apps/minunit/bin
    - cp bin/cbmc /tmp/apps/minunit/bin
    - cd /tmp
    - git clone https://github.com/nanolith/modelcheck modelcheck
    - cd modelcheck && git checkout v0.1.0
    - mkdir build && cd build
    - CC=gcc-8 CXX=g++-8 cmake -DCMAKE_INSTALL_PREFIX=/tmp/apps/minunit ..
    - make && make install
    - cd /tmp

jobs:
    include:

        - &build-and-test
            stage: Build and test
            install:
            script:
                mkdir build && cd build
                CC=gcc-8 CXX=g++-8 cmake -DCMAKE_INSTALL_PREFIX=/tmp/apps/minunit -DCMAKE_PREFIX_PATH=/tmp/apps/minunit ..
                make && make run_tests
